### ISSUE TITLE
Send confirmation email to user upon signup

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/prisma-auth#15]
Before a user is allowed to login, they should receive a confirmation email. Until then the user is not allowed to login.

Many services nowadays allow you to confirm your email later, and you still may login. Perhaps we should make it optional?

**Comment by RogerKemp** [comment]
If you make it optional it requires additional steps:

- Keep track of when user signed up
- Send reminder(s)
- Lock user out after a certain period

**Comment by SpaceK33z** [comment]
> Keep track of when user signed up

Good one, created #17 for that.

> Send reminder(s)
> Lock user out after a certain period

E.g. on Twitter they'll just harass you with a warning and forbid you to use some features (AFAIK). I'll leave it up to the project to implement a way to nag the user.

**Comment by RogerKemp** [comment]
Ok, but you have to do something, otherwise it doesn't make any sense to use the confirmation?

**Comment by SpaceK33z** [comment]
Yes. I think I'll also make an option (off by default I guess, or on?) which makes it required to confirm your email before logging in.
