### ISSUE TITLE
name field in signup mutation taking email value

### ISSUE THREAD

**Issue by email2vimalraj** [Volst/prisma-auth#20]
Consider the following mutation: 

```
mutation signup {
  signup(data: {
    email: "mymail@example.com",
    name: "Vimalraj",
    password: "#########"
  }) {
    token
  }
}
```

Then query the user with the proper header:

```
query currentUser {
  currentUser {
    name
  }
}
```

**Expected Behavior**
Expecting the query should return `Vimalraj`

**Actual Behavior**
It returns `mymail@example.com`.

**Comment by email2vimalraj** [comment]
I'm raising a Pull request for this issue. If you agree with the change, kindly merge the pull request.

**Comment by SpaceK33z** [comment]
Ah yes, that's a bug!
