### ISSUE TITLE
ECONNREFUSED 127.0.0.1:4466

### ISSUE THREAD

**Issue by gHashTag** [Volst/prisma-auth#30]
#### downloaded the project:
```git clone https://github.com/Volst/prisma-auth.git```

#### next:
```yarn install```

#### next:
```yarn start```
Server is running on http://localhost:4000

#### next:
```javascript
mutation {
  signup(data: {
    email: "qwerty@icloud.com",
    password: "qwerty",
    name: "Playra"
  })
  {
    token
  }
}
```

request to http://localhost:4466/ failed, reason: connect ECONNREFUSED 127.0.0.1:4466

**Comment by SpaceK33z** [comment]
Hey, yes you need to start docker-compose in the example. After it has started you also need to run `npm i -g prisma && prisma deploy` in that repostory.

I will keep this open so I know I need to add a README to the example to clarify this.

**Comment by gHashTag** [comment]
after prisma deploy:
 ▸    Could not connect to server at http://localhost:4466. Please check if your server is running.
but my server running Server is running on http://localhost:4000

Something wrong with the ports or am I wrong somewhere?

**Comment by SpaceK33z** [comment]
Port 4466 is the port the Prisma service should be running on. After Docker has started you should be able to navigate to http://localhost:4466. It could take a while if it needs to boot for the first time. I don't know exactly what is going wrong in your situation though.

**Comment by gHashTag** [comment]
Cannot query field 'signup' on type

![2018-06-29 18 28 41](https://user-images.githubusercontent.com/6774813/42100987-69cc89a6-7bca-11e8-88e8-9e59aa61a196.png)
